example:
  property: I AM DEV

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin